### ISSUE TITLE
could not load the voting interface

### ISSUE THREAD

**Issue by daizhiwei123456** [TheBojda/zktree-vote#6]
Hello author, I did not report an error when replicating your code, but I ![微信图片_20240117173501](https://github.com/TheBojda/zktree-vote/assets/127122285/d2749204-f3e3-43be-a930-773ac7af548f)
![微信图片_20240117173501](https://github.com/TheBojda/zktree-vote/assets/127122285/1eb20dc2-1022-4907-b459-bb7a5b28a465)

**Comment by daizhiwei123456** [comment]
![Uploading 微信图片_20240117173906.png…]()

**Comment by daizhiwei123456** [comment]
![Uploading 微信图片_20240117173906.png…]()

**Comment by TheBojda** [comment]
It is hard to say the problem with these 2 empty screenshots without error messages. :)

**Comment by daizhiwei123456** [comment]
17/5000
No error was reported, but the interface could not be loaded
![微信图片_20240118152023](https://github.com/TheBojda/zktree-vote/assets/127122285/5696ee44-f986-4f52-88ee-52599353594a)

**Comment by dada-1** [comment]
> 17/5000 No error was reported, but the interface could not be loaded ![微信图片_20240118152023](https://private-user-images.githubusercontent.com/127122285/297656667-5696ee44-f986-4f52-88ee-52599353594a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODA0MTAsIm5iZiI6MTcwNTk4MDExMCwicGF0aCI6Ii8xMjcxMjIyODUvMjk3NjU2NjY3LTU2OTZlZTQ0LWY5ODYtNGY1Mi04OGVlLTUyNTk5MzUzNTk0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMzIxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjUwZTU2M2U2YjNhNGRiODMwNzkyYWRlNDcyOTI5MzE1MjNiYzM5NDQ1Y2Y1OTVmZjJjYjM1NzQ2NDM1MDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jAvs0Oai0QZ93WbMeGDfiikIlyrelCLBJKfRpxRjOR0)

Are you able to solve this issue now?

**Comment by BurnhamZhang** [comment]
> 17/5000 No error was reported, but the interface could not be loaded ![微信图片_20240118152023](https://private-user-images.githubusercontent.com/127122285/297656667-5696ee44-f986-4f52-88ee-52599353594a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTM5NzcsIm5iZiI6MTcwOTA5MzY3NywicGF0aCI6Ii8xMjcxMjIyODUvMjk3NjU2NjY3LTU2OTZlZTQ0LWY5ODYtNGY1Mi04OGVlLTUyNTk5MzUzNTk0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwNDE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTE2MzU2MDc1MmEzM2YyYjIzNGViODhkNjE1MmIxMzMzNGMxNWY3YWFhN2ZhN2Y5OGU3MzgwMTRhZjRkMTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MJ7ClPrCveC_PGYbzGjHUN_uOcby4zqsyd2a_pEDoyg)

before npm start ,npm run build ,我跑起来了，先要build才可以

**Comment by Dev-rahul** [comment]
I have the same issue. I found that while npm run prepare there occurs a type error with snarkjs

[INFO]  snarkJS: Reading r1cs
[INFO]  snarkJS: Reading tauG1
[INFO]  snarkJS: Reading tauG2
[INFO]  snarkJS: Reading alphatauG1
[INFO]  snarkJS: Reading betatauG1
[INFO]  snarkJS: Circuit hash: 
                b71cd525 8500a879 96730216 6f1e0dd4
                22034732 4a123b52 f824199f 08954033
                27630f78 d1d275f6 4f6467c1 fe9f0220
                791678bb 5aaa4a43 bf661459 fbc35f58
node:internal/validators:95
      throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received an instance of Uint8Array
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:187:24)
    at /Users/rahulmurali/Documents/Uni Works/zktree-vote/node_modules/snarkjs/build/cli.cjs:8292:13 {
  code: 'ERR_INVALID_ARG_TYPE'
}

any help would be apreicated

**Comment by cosmatudor** [comment]
> I have the same issue. I found that while npm run prepare there occurs a type error with snarkjs
> 
> [INFO] snarkJS: Reading r1cs [INFO] snarkJS: Reading tauG1 [INFO] snarkJS: Reading tauG2 [INFO] snarkJS: Reading alphatauG1 [INFO] snarkJS: Reading betatauG1 [INFO] snarkJS: Circuit hash: b71cd525 8500a879 96730216 6f1e0dd4 22034732 4a123b52 f824199f 08954033 27630f78 d1d275f6 4f6467c1 fe9f0220 791678bb 5aaa4a43 bf661459 fbc35f58 node:internal/validators:95 throw new ERR_INVALID_ARG_TYPE(name, 'number', value); ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received an instance of Uint8Array at process.set [as exitCode] (node:internal/bootstrap/node:123:9) at process.exit (node:internal/process/per_thread:187:24) at /Users/rahulmurali/Documents/Uni Works/zktree-vote/node_modules/snarkjs/build/cli.cjs:8292:13 { code: 'ERR_INVALID_ARG_TYPE' }
> 
> any help would be apreicated

I solved this error by installing the latest version of snarkjs
```npm install snarkjs@latest --save```
